import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const TRANSLATIONS = {
  en: {
    appTitle: "MTC-LEDGER",
    appSub: "Tiffin & Catering Register",
    goodMorning: "Good Morning 🌅",
    goodEvening: "Good Evening 🌆",
    todayLunch: "Today's Lunch",
    todayDinner: "Today's Dinner",
    todayIncome: "Today's Tiffin Income",
    todayExpense: "Today's Expense",
    todayProfit: "Today's Profit",
    pendingPayments: "Pending Customer Payments",
    upcomingCatering: "Upcoming Catering",
    orders: "Orders",
    quickActions: "Quick Actions",
    addCustomer: "+ Customer",
    lunchBtn: "🍱 Lunch",
    dinnerBtn: "🍱 Dinner",
    addExpense: "+ Expense",
    addCatering: "+ Catering",
    receivePayment: "💰 Payment",
    confirmed: "Confirmed",
    notRequired: "Not Required",
    skipped: "Skipped",
    totalCustomers: "Total Customers",
    confirmLunch: "Confirm Lunch",
    confirmDinner: "Confirm Dinner",
    customerName: "Customer Name",
    mobileNumber: "Mobile Number",
    address: "Address",
    area: "Area",
    landmark: "Landmark",
    lunchPrice: "Lunch Price (₹)",
    dinnerPrice: "Dinner Price (₹)",
    defaultQty: "Default Quantity",
    startDate: "Start Date",
    notes: "Notes / Preferences",
    status: "Status",
    active: "Active",
    paused: "Paused",
    inactive: "Inactive",
    pauseCustomer: "Pause Customer",
    pauseFrom: "Pause From",
    pauseUntil: "Pause Until",
    unpause: "Resume / Unpause",
    thisMonth: "This Month",
    totalBill: "Total Bill",
    paid: "Paid",
    pending: "Pending",
    viewLedger: "View Ledger",
    edit: "Edit",
    save: "Save Details",
    cancel: "Cancel",
    searchCustomer: "Search customer by name or mobile...",
    categories: "Categories",
    amount: "Amount (₹)",
    category: "Category",
    paymentMode: "Payment Mode",
    cash: "Cash 💵",
    upi: "UPI 📱",
    bank: "Bank 🏦",
    totalExpenseToday: "Total Expense Today",
    cateringOrders: "Catering Orders",
    upcoming: "Upcoming",
    completed: "Completed",
    cancelled: "Cancelled",
    addCateringOrder: "+ Add Catering Order",
    eventName: "Event Name",
    eventType: "Event Type",
    eventDate: "Event Date",
    eventTime: "Event Time",
    venue: "Venue / Address",
    plates: "Number of Plates",
    ratePerPlate: "Rate Per Plate (₹)",
    menu: "Menu Items",
    extraCharges: "Extra Charges (₹)",
    discount: "Discount (₹)",
    subtotal: "Subtotal",
    totalAmount: "Total Amount",
    advancePaid: "Advance Paid (₹)",
    balanceDue: "Balance Due",
    todaySummary: "Today's Business Summary",
    netProfit: "Net Profit",
    reports: "Business Reports",
    dailyReport: "Daily Report",
    monthlyReport: "Monthly Report",
    customerReport: "Customer Report",
    expenseReport: "Expense Report",
    exportPDF: "Export PDF 📄",
    exportExcel: "Export Excel 📊",
    yes: "YES ✅",
    no: "NO ❌",
    language: "Language / भाषा",
    logout: "Logout",
    loginTitle: "MTC-LEDGER",
    loginSub: "Sign in to access digital register",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    loginBtn: "Sign In",
    quickDemoLogin: "⚡ Single Tap Quick Admin Login"
  },
  hi: {
    appTitle: "MTC-LEDGER",
    appSub: "टिफिन एवं कैटरिंग रजिस्टर",
    goodMorning: "शुभ प्रभात 🌅",
    goodEvening: "शुभ संध्या 🌆",
    todayLunch: "आज का लंच",
    todayDinner: "आज का डिनर",
    todayIncome: "आज की टिफिन आमदनी",
    todayExpense: "आज का कुल खर्चा",
    todayProfit: "आज का शुद्ध मुनाफा",
    pendingPayments: "कुल बाकी ग्राहक भुगतान",
    upcomingCatering: "आगामी कैटरिंग ऑर्डर",
    orders: "ऑर्डर",
    quickActions: "त्वरित कार्य (Quick Actions)",
    addCustomer: "+ ग्राहक जोड़ें",
    lunchBtn: "🍱 लंच",
    dinnerBtn: "🍱 डिनर",
    addExpense: "+ खर्चा जोड़ें",
    addCatering: "+ कैटरिंग",
    receivePayment: "💰 भुगतान प्राप्त करें",
    confirmed: "कन्फर्म (भिजवाया)",
    notRequired: "आवश्यकता नहीं (Skip)",
    skipped: "नहीं चाहिए",
    totalCustomers: "कुल ग्राहक",
    confirmLunch: "लंच सहेजें / Confirm Lunch",
    confirmDinner: "डिनर सहेजें / Confirm Dinner",
    customerName: "ग्राहक का नाम",
    mobileNumber: "मोबाइल नंबर",
    address: "पता (Address)",
    area: "इलाका / Area",
    landmark: "लैंडमार्क / पास की जगह",
    lunchPrice: "लंच दर (₹)",
    dinnerPrice: "डिनर दर (₹)",
    defaultQty: "सामान्य टिफिन संख्या",
    startDate: "शुरुआत तिथि",
    notes: "विशेष टिप / Notes",
    status: "स्थिति / Status",
    active: "सक्रिय (Active)",
    paused: "रोक पर (Paused)",
    inactive: "निष्क्रिय (Inactive)",
    pauseCustomer: "टिफिन कुछ दिन रोकें",
    pauseFrom: "कब से रोकें",
    pauseUntil: "कब तक रोकें",
    unpause: "पुनः चालू करें (Resume)",
    thisMonth: "इस महीने का हिसाब",
    totalBill: "कुल बिल",
    paid: "प्राप्त जमा",
    pending: "बाकी राशि",
    viewLedger: "खाता देखें (Ledger)",
    edit: "बदलाव करें",
    save: "सहेजें (Save)",
    cancel: "रद्द करें",
    searchCustomer: "नाम या नंबर से ग्राहक खोजें...",
    categories: "श्रेणियां",
    amount: "राशि (₹)",
    category: "खर्चे की श्रेणी",
    paymentMode: "भुगतान माध्यम",
    cash: "नकद (Cash) 💵",
    upi: "UPI (Google Pay/PhonePe) 📱",
    bank: "बैंक ट्रांसफर 🏦",
    totalExpenseToday: "आज का कुल खर्चा",
    cateringOrders: "कैटरिंग बुकिंग",
    upcoming: "आगामी बुकिंग",
    completed: "संपन्न",
    cancelled: "रद्द",
    addCateringOrder: "+ नई कैटरिंग बुकिंग",
    eventName: "कार्यक्रम नाम",
    eventType: "प्रकार (शादी/जन्मदिन/पार्टी)",
    eventDate: "कार्यक्रम तिथि",
    eventTime: "समय",
    venue: "स्थान / Venue",
    plates: "प्लेट्स की संख्या",
    ratePerPlate: "प्रति प्लेट दर (₹)",
    menu: "मेनू आइटम list",
    extraCharges: "अन्य चार्ज (₹)",
    discount: "छूट / Discount (₹)",
    subtotal: "कुल योग",
    totalAmount: "अंतिम कुल राशि",
    advancePaid: "अग्रिम प्राप्त (Advance)",
    balanceDue: "बाकी भुगतान",
    todaySummary: "आज का व्यापार सारांश",
    netProfit: "शुद्ध लाभ (Profit)",
    reports: "व्यापार रिपोर्ट्स",
    dailyReport: "दैनिक रिपोर्ट",
    monthlyReport: "मासिक रिपोर्ट",
    customerReport: "ग्राहक बिल रिपोर्ट",
    expenseReport: "खर्चा रिपोर्ट",
    exportPDF: "PDF डाउनलोड करें 📄",
    exportExcel: "Excel डाउनलोड करें 📊",
    yes: "हाँ (YES) ✅",
    no: "नहीं (NO) ❌",
    language: "भाषा / Language",
    logout: "लॉगआउट करें",
    loginTitle: "MTC-LEDGER",
    loginSub: "डिजिटल रजिस्टर उपयोग करने के लिए लॉगिन करें",
    emailLabel: "ईमेल आईडी",
    passwordLabel: "पासवर्ड",
    loginBtn: "लॉगिन करें",
    quickDemoLogin: "⚡ एक क्लिक में एडमिन लॉगिन"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('papa_lang') || 'en');

  const toggleLanguage = () => {
    const nextLang = lang === 'en' ? 'hi' : 'en';
    setLang(nextLang);
    localStorage.setItem('papa_lang', nextLang);
  };

  const t = (key) => {
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
